### ISSUE TITLE
Inability to use external stylesheets is a major slowdown

### ISSUE THREAD

**Issue by dualyticalchemy** [hybridsjs/hybrids#107]
Maybe it's just Parcel, but neither Tachyons nor Milligram works for `<button>`s by CDN in the unusual copy-paste to HTML workflow nor when included by `<link rel="stylesheet" href="{link/to/local/path}" />`

**Comment by smalluban** [comment]
Technically using external CSS inside of the Shadow DOM works just fine. The problem is different. So far CSS frameworks are not prepared specifically to be used inside of the Shadow DOM. For example, `Milligram`, which you mentioned define main styles, which has to be set on Light DOM (specifically for `body` and `html` elements):

```css
html {
  box-sizing: border-box;
  font-size: 62.5%;
}

body {
  color: #606c76;
  font-family: 'Roboto', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;
  font-size: 1.6em;
  font-weight: 300;
  letter-spacing: .01em;
  line-height: 1.6;
}
```

For the obvious reasons those elements can't be inside of your web components, so other styles will not inherit those properties (the font-size is crucial, as other selectors use `rem` sizing). However, if you attach the CSS both in the document and your custom elements it will work.

I prepared a working example here: https://codesandbox.io/s/web-component-with-external-styles-bzwfo?file=/components/SimpleCounter.js

I don't recommend linking external styles for yet another reason - you include the whole library to each instance of your element. Some of the CSS libraries have separate files for specific components. How to include external files into the web component you find in the [hybrids documentation](https://hybrids.js.org/template-engine/styling#css-stylesheet).
